<?php


namespace Tools4Schools\Graph\Introspection;


use Tools4Schools\Graph\Contracts\Schema\Types\ObjectType as ObjectTypeContract;
use Tools4Schools\Graph\Schema\Types\ObjectType;
use Tools4Schools\Graph\Types\QueryType;
use Tools4Schools\Graph\Fields\Text;

class Type extends QueryType
{
    public $type = ObjectType::class;


    public function __construct()
    {
        parent::__construct('__type');
    }

    protected function args(): array
    {
        return [
            'name' =>Text::make()->required(),
        ];
    }

    protected function resolver(ObjectTypeContract $parent = null, array $arguments = [], $context = null, $info = null)
    {
        $this->type = $parent->value['kind'];

        return parent::resolver($parent, $arguments, $context, $info); // TODO: Change the autogenerated stub
    }
}