<?php


namespace Tools4Schools\Graph\Fields;


use Tools4Schools\Graph\ObjectType;
use Tools4Schools\Graph\Contracts\Schema\Types\Type;


//returns a collection of multiple objects
class HasMany extends RelationField
{
    protected $type;

    public function type()
    {
        return $this->type;
    }

    public function __construct(Type $relationType, string $name = null, string $attribute = null, $resolveCallback = null)
    {
        $this->type = $relationType;
        if(is_null($name))
        {
            $name = $relationType->name();
        }
        parent::__construct($name, $attribute, $resolveCallback);
    }

   /* public function resolve(Type $parent = null, array $arguments = [], $context = null, $info = null)
    {
        dump($parent);
        //return parent::resolve($parent, $arguments, $context, $info); // TODO: Change the autogenerated stub
    }
    /* public function resolve($resource, $attribute = null): void
     {
         // type.resolve(this)
     }*/
}