<?php


namespace Tools4Schools\Graph;


use Tools4Schools\Graph\Language\AST\Node;

abstract class EloquentType extends Type
{

    public function resolve(Node $requestNode)
    {

        foreach ($requestNode->getSelectionSet() as $selection) {
            dump($selection)
        }


        // foreach $requestNode->selectionset() as selection
        // if this ->has field(selection->name())
        //this->getField(selection->name)->resolve()
        
        //parent::resolve($requestNode); // TODO: Change the autogenerated stub
    }
}